# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: channy's Blog
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "" # the subpath of the site
url: "https://channy93.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.png
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Blog
    - name: Work

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: whdckskc2@gmail.com
      link: mailto:whdckskfc2@gmail.com
    - name: Kakao
      value: whdckskfc
      link: "#"
  follow:
    - name: Instagram
      link: https://www.instagram.com/chanismm93/
      username: "@chanismm93"
    - name: Facebook
      link: http://facebook.com/jongchan93
    - name: LinkedIn
      link: http://linkedin.com/in/jc-park-b6b67b20a
    - name: GitHub
      link: http://github.com/channy93


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
